
package com.fr.hailian.rtxWebService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-24T10:33:33.793+08:00
 * Generated source version: 3.1.12
 * 
 */
public final class IMServiceSoap_IMServiceSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://www.nwh.cn/Rpc", "IMService");

    private IMServiceSoap_IMServiceSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = IMService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        IMService ss = new IMService(wsdlURL, SERVICE_NAME);
        IMServiceSoap port = ss.getIMServiceSoap();  
        
        {
        System.out.println("Invoking sendMessage...");
        java.lang.String _sendMessage_info = "";
        java.lang.String _sendMessage__return = port.sendMessage(_sendMessage_info);
        System.out.println("sendMessage.result=" + _sendMessage__return);


        }
        {
        System.out.println("Invoking sendMessageToUser...");
        java.lang.String _sendMessageToUser_taskTitle = "";
        java.lang.String _sendMessageToUser_msgContent = "";
        java.lang.String _sendMessageToUser_transUrl = "";
        java.lang.String _sendMessageToUser_userName = "";
        java.lang.String _sendMessageToUser_userList = "";
        java.lang.String _sendMessageToUser_from = "";
        java.lang.String _sendMessageToUser_smsType = "";
        java.lang.String _sendMessageToUser_sendSMSTime = "";
        java.lang.String _sendMessageToUser_businessId = "";
        int _sendMessageToUser_rank = 0;
        java.lang.String _sendMessageToUser__return = port.sendMessageToUser(_sendMessageToUser_taskTitle, _sendMessageToUser_msgContent, _sendMessageToUser_transUrl, _sendMessageToUser_userName, _sendMessageToUser_userList, _sendMessageToUser_from, _sendMessageToUser_smsType, _sendMessageToUser_sendSMSTime, _sendMessageToUser_businessId, _sendMessageToUser_rank);
        System.out.println("sendMessageToUser.result=" + _sendMessageToUser__return);


        }

        System.exit(0);
    }

}
