
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.fr.hailian.rtxWebService;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-24T10:33:33.822+08:00
 * Generated source version: 3.1.12
 * 
 */

@javax.jws.WebService(
                      serviceName = "IMService",
                      portName = "IMServiceSoap12",
                      targetNamespace = "http://www.nwh.cn/Rpc",
                      wsdlLocation = "http://10.0.6.41:8089/NWHServiceIM.asmx?wsdl",
                      endpointInterface = "com.fr.hailian.rtxWebService.IMServiceSoap")
                      
public class IMServiceSoap12Impl implements IMServiceSoap {

    private static final Logger LOG = Logger.getLogger(IMServiceSoap12Impl.class.getName());

    /* (non-Javadoc)
     * @see com.fr.hailian.rtxWebService.IMServiceSoap#sendMessage(java.lang.String info)*
     */
    public java.lang.String sendMessage(java.lang.String info) { 
        LOG.info("Executing operation sendMessage");
        System.out.println(info);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.fr.hailian.rtxWebService.IMServiceSoap#sendMessageToUser(java.lang.String taskTitle, java.lang.String msgContent, java.lang.String transUrl, java.lang.String userName, java.lang.String userList, java.lang.String from, java.lang.String smsType, java.lang.String sendSMSTime, java.lang.String businessId, int rank)*
     */
    public java.lang.String sendMessageToUser(java.lang.String taskTitle, java.lang.String msgContent, java.lang.String transUrl, java.lang.String userName, java.lang.String userList, java.lang.String from, java.lang.String smsType, java.lang.String sendSMSTime, java.lang.String businessId, int rank) { 
        LOG.info("Executing operation sendMessageToUser");
        System.out.println(taskTitle);
        System.out.println(msgContent);
        System.out.println(transUrl);
        System.out.println(userName);
        System.out.println(userList);
        System.out.println(from);
        System.out.println(smsType);
        System.out.println(sendSMSTime);
        System.out.println(businessId);
        System.out.println(rank);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
