package com.fr.hailian.rtxWebService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-24T10:33:33.827+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://www.nwh.cn/Rpc", name = "IMServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface IMServiceSoap {

    @WebMethod(operationName = "SendMessage", action = "http://www.nwh.cn/Rpc/SendMessage")
    @RequestWrapper(localName = "SendMessage", targetNamespace = "http://www.nwh.cn/Rpc", className = "com.fr.hailian.rtxWebService.SendMessage")
    @ResponseWrapper(localName = "SendMessageResponse", targetNamespace = "http://www.nwh.cn/Rpc", className = "com.fr.hailian.rtxWebService.SendMessageResponse")
    @WebResult(name = "SendMessageResult", targetNamespace = "http://www.nwh.cn/Rpc")
    public java.lang.String sendMessage(
        @WebParam(name = "info", targetNamespace = "http://www.nwh.cn/Rpc")
        java.lang.String info
    );

    @WebMethod(operationName = "SendMessageToUser", action = "http://www.nwh.cn/Rpc/SendMessageToUser")
    @RequestWrapper(localName = "SendMessageToUser", targetNamespace = "http://www.nwh.cn/Rpc", className = "com.fr.hailian.rtxWebService.SendMessageToUser")
    @ResponseWrapper(localName = "SendMessageToUserResponse", targetNamespace = "http://www.nwh.cn/Rpc", className = "com.fr.hailian.rtxWebService.SendMessageToUserResponse")
    @WebResult(name = "SendMessageToUserResult", targetNamespace = "http://www.nwh.cn/Rpc")
    public java.lang.String sendMessageToUser(
        @WebParam(name = "TaskTitle", targetNamespace = "http://www.nwh.cn/Rpc")
        java.lang.String taskTitle,
        @WebParam(name = "MsgContent", targetNamespace = "http://www.nwh.cn/Rpc")
        java.lang.String msgContent,
        @WebParam(name = "TransUrl", targetNamespace = "http://www.nwh.cn/Rpc")
        java.lang.String transUrl,
        @WebParam(name = "UserName", targetNamespace = "http://www.nwh.cn/Rpc")
        java.lang.String userName,
        @WebParam(name = "UserList", targetNamespace = "http://www.nwh.cn/Rpc")
        java.lang.String userList,
        @WebParam(name = "From", targetNamespace = "http://www.nwh.cn/Rpc")
        java.lang.String from,
        @WebParam(name = "SMSType", targetNamespace = "http://www.nwh.cn/Rpc")
        java.lang.String smsType,
        @WebParam(name = "SendSMSTime", targetNamespace = "http://www.nwh.cn/Rpc")
        java.lang.String sendSMSTime,
        @WebParam(name = "BusinessId", targetNamespace = "http://www.nwh.cn/Rpc")
        java.lang.String businessId,
        @WebParam(name = "Rank", targetNamespace = "http://www.nwh.cn/Rpc")
        int rank
    );
}
