package com.fr.hailian.ssoWebService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-08T15:22:48.132+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://sso.nwh.cn", name = "SSOServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface SSOServiceSoap {

    @WebMethod(action = "http://sso.nwh.cn/getTargetEntry")
    @RequestWrapper(localName = "getTargetEntry", targetNamespace = "http://sso.nwh.cn", className = "com.fr.hailiann.webservice.GetTargetEntry")
    @ResponseWrapper(localName = "getTargetEntryResponse", targetNamespace = "http://sso.nwh.cn", className = "com.fr.hailiann.webservice.GetTargetEntryResponse")
    @WebResult(name = "getTargetEntryResult", targetNamespace = "http://sso.nwh.cn")
    public java.lang.String getTargetEntry(
        @WebParam(name = "info", targetNamespace = "http://sso.nwh.cn")
        java.lang.String info
    );

    @WebMethod(action = "http://sso.nwh.cn/getUserInfoByToken")
    @RequestWrapper(localName = "getUserInfoByToken", targetNamespace = "http://sso.nwh.cn", className = "com.fr.hailiann.webservice.GetUserInfoByToken")
    @ResponseWrapper(localName = "getUserInfoByTokenResponse", targetNamespace = "http://sso.nwh.cn", className = "com.fr.hailiann.webservice.GetUserInfoByTokenResponse")
    @WebResult(name = "getUserInfoByTokenResult", targetNamespace = "http://sso.nwh.cn")
    public java.lang.String getUserInfoByToken(
        @WebParam(name = "info", targetNamespace = "http://sso.nwh.cn")
        java.lang.String info
    );

    @WebMethod(operationName = "HelloWorld", action = "http://sso.nwh.cn/HelloWorld")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://sso.nwh.cn", className = "com.fr.hailiann.webservice.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://sso.nwh.cn", className = "com.fr.hailiann.webservice.HelloWorldResponse")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://sso.nwh.cn")
    public java.lang.String helloWorld(
        @WebParam(name = "msg", targetNamespace = "http://sso.nwh.cn")
        java.lang.String msg
    );

    @WebMethod(action = "http://sso.nwh.cn/changePassword")
    @RequestWrapper(localName = "changePassword", targetNamespace = "http://sso.nwh.cn", className = "com.fr.hailiann.webservice.ChangePassword")
    @ResponseWrapper(localName = "changePasswordResponse", targetNamespace = "http://sso.nwh.cn", className = "com.fr.hailiann.webservice.ChangePasswordResponse")
    @WebResult(name = "changePasswordResult", targetNamespace = "http://sso.nwh.cn")
    public java.lang.String changePassword(
        @WebParam(name = "loginName", targetNamespace = "http://sso.nwh.cn")
        java.lang.String loginName,
        @WebParam(name = "oldPasswd", targetNamespace = "http://sso.nwh.cn")
        java.lang.String oldPasswd,
        @WebParam(name = "newPasswd", targetNamespace = "http://sso.nwh.cn")
        java.lang.String newPasswd
    );

    @WebMethod(action = "http://sso.nwh.cn/getUserResource")
    @RequestWrapper(localName = "getUserResource", targetNamespace = "http://sso.nwh.cn", className = "com.fr.hailiann.webservice.GetUserResource")
    @ResponseWrapper(localName = "getUserResourceResponse", targetNamespace = "http://sso.nwh.cn", className = "com.fr.hailiann.webservice.GetUserResourceResponse")
    @WebResult(name = "getUserResourceResult", targetNamespace = "http://sso.nwh.cn")
    public java.lang.String getUserResource(
        @WebParam(name = "info", targetNamespace = "http://sso.nwh.cn")
        java.lang.String info
    );

    @WebMethod(action = "http://sso.nwh.cn/getUserState")
    @RequestWrapper(localName = "getUserState", targetNamespace = "http://sso.nwh.cn", className = "com.fr.hailiann.webservice.GetUserState")
    @ResponseWrapper(localName = "getUserStateResponse", targetNamespace = "http://sso.nwh.cn", className = "com.fr.hailiann.webservice.GetUserStateResponse")
    @WebResult(name = "getUserStateResult", targetNamespace = "http://sso.nwh.cn")
    public java.lang.String getUserState(
        @WebParam(name = "loginName", targetNamespace = "http://sso.nwh.cn")
        java.lang.String loginName
    );

    @WebMethod(action = "http://sso.nwh.cn/userValidate")
    @RequestWrapper(localName = "userValidate", targetNamespace = "http://sso.nwh.cn", className = "com.fr.hailiann.webservice.UserValidate")
    @ResponseWrapper(localName = "userValidateResponse", targetNamespace = "http://sso.nwh.cn", className = "com.fr.hailiann.webservice.UserValidateResponse")
    @WebResult(name = "userValidateResult", targetNamespace = "http://sso.nwh.cn")
    public java.lang.String userValidate(
        @WebParam(name = "info", targetNamespace = "http://sso.nwh.cn")
        java.lang.String info
    );

    @WebMethod(action = "http://sso.nwh.cn/logout")
    @RequestWrapper(localName = "logout", targetNamespace = "http://sso.nwh.cn", className = "com.fr.hailiann.webservice.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://sso.nwh.cn", className = "com.fr.hailiann.webservice.LogoutResponse")
    @WebResult(name = "logoutResult", targetNamespace = "http://sso.nwh.cn")
    public java.lang.String logout(
        @WebParam(name = "info", targetNamespace = "http://sso.nwh.cn")
        java.lang.String info
    );
}
