package com.fr.hailian.ssoWebService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-08T15:22:48.148+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "SSOService", 
                  wsdlLocation = "http://10.0.6.19:8008/SSOService.asmx?WSDL",
                  targetNamespace = "http://sso.nwh.cn") 
public class SSOService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://sso.nwh.cn", "SSOService");
    public final static QName SSOServiceSoap12 = new QName("http://sso.nwh.cn", "SSOServiceSoap12");
    public final static QName SSOServiceSoap = new QName("http://sso.nwh.cn", "SSOServiceSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://10.0.6.19:8008/SSOService.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SSOService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.0.6.19:8008/SSOService.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public SSOService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SSOService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SSOService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SSOService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SSOService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SSOService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns SSOServiceSoap
     */
    @WebEndpoint(name = "SSOServiceSoap12")
    public SSOServiceSoap getSSOServiceSoap12() {
        return super.getPort(SSOServiceSoap12, SSOServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SSOServiceSoap
     */
    @WebEndpoint(name = "SSOServiceSoap12")
    public SSOServiceSoap getSSOServiceSoap12(WebServiceFeature... features) {
        return super.getPort(SSOServiceSoap12, SSOServiceSoap.class, features);
    }


    /**
     *
     * @return
     *     returns SSOServiceSoap
     */
    @WebEndpoint(name = "SSOServiceSoap")
    public SSOServiceSoap getSSOServiceSoap() {
        return super.getPort(SSOServiceSoap, SSOServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SSOServiceSoap
     */
    @WebEndpoint(name = "SSOServiceSoap")
    public SSOServiceSoap getSSOServiceSoap(WebServiceFeature... features) {
        return super.getPort(SSOServiceSoap, SSOServiceSoap.class, features);
    }

}
